### ISSUE TITLE
Can't unmount

### ISSUE THREAD

**Issue by ghost** [CheezeCake/suamd#2]
Permission denied.

**Comment by CheezeCake** [comment]
Could you give me the steps to follow to reproduce this error ?

**Comment by ghost** [comment]
All right, sorry about that. Well, I've installed it by

```
sudo make install
```

Then started it (by dmenu); plugged a usb key; it's been mounted on /media. But then trying to unmount it via right clicking on pcmanfm-qt file manager has failed stating something like "permission denied". I could unmount it by issuing in terminal

```
sudo umount -t ext4 /dev/sdb1 /media
```

**Comment by CheezeCake** [comment]
I think that pcmanfm is using something that does not require root permission to mounting/unmount the device (udisks2 maybe), that's why it cannot unmount it.

The unmounting should be done automatically when you unplug the device.
Of course, unmounting before unpluging the device would be much safer, but suamd was intended to be something that did not require any manual intervention.
I wanted usb devices to be mounted in /media when I would plug them in my raspberry pi (which runs as a headless server), and unmounted when I would unplug them. I just make sure that no reading or wrinting on the device is happening begore unpluging it. Only the streaming service I use would access the devices, if I'm not streaming any content, it's safe to unplug them.

It's probably not very well suited for desktop use.

**Comment by ghost** [comment]
Not a big issue really. Launching pcman as root solves it; then unmounting works. Thank you.

**Comment by CheezeCake** [comment]
Very well, I'm glad you're using it.
